### ISSUE TITLE
Bug with Redactor Editor

### ISSUE THREAD

**Issue by jenswittmann** [craftsmancoding/assetmanager#68]
Hello,
i installed Redactor Editor form modmore today. After installing i cant scroll by editing resources. The following error appears in the chrome browser log:

`Uncaught TypeError: jQuery(...).sortable is not a function app.js:61 (assman/js/app.js)`

Maybe the function will be used twice?

Cheers
Jens

**Comment by Mark-H** [comment]
Relevant: #60 #61

It looks like there simply needs to be a new release

**Comment by fireproofsocks** [comment]
Likely one of my many festering todo's... ;)

**Comment by crecorn** [comment]
Any time frame in getting the new release out? I like the add-on but the js issue keeps causing problems.

**Comment by fireproofsocks** [comment]
Time frames are driven by paid projects, so if you'd like the update you have several options:

1. Initiate a paid project
2. Install and update the plugin using Repoman as it allows for more direct updates via Git 
3. Fork the project and install your own version of it.

Otherwise, I'll get to it when I get to it.

**Comment by Mark-H** [comment]
Would a bug bounty of say $20 be enough to warrant a release?

**Comment by crecorn** [comment]
I'll donate to that. I'd like to start using it again. It's great for
creating galleries.

Mike Tarantino
IM Image Marketing
330 272-1493
www.iMimagemarketing.com <http://www.imimagemarketing.com>
www.iMvideotransfer.com <http://www.IMvideotransfer.com>
www.townshopperplus.com

**Comment by Mark-H** [comment]
@fireproofsocks I understand where you're coming from when you say paid projects drive time frames (that's exactly why I made releasing and supporting extras my primary business, rather than a thing on the side, as I enjoy making extras more), but I would like to ask you again if you could please release an update to MODX.com.

From the looks of github, there's a lot of great fixes and improvements (not just for this issue with Redactor) pending, and I'm sure your users would very much appreciate getting access to those. 

I wasn't kidding with the bug bounty and have placed it on bountysource: https://www.bountysource.com/issues/27155879-bug-with-redactor-editor

**Comment by crecorn** [comment]
@fireproofsocks I added to the fund on bounty source. @Mark-H Thanks for doing this. I really like this plugin and redactor.

**Comment by Mark-H** [comment]
@fireproofsocks Do you mind if I update the release on MODX.com for you?  

I'd rather not as I wouldn't want anyone updating my extras without my permission, however it's been over 14 months since this issue was fixed with no sign of you finding the time to issue a release, despite a $40 bounty being available. 

We're still getting people who run into this issue and I'm getting tired of asking them to manually patch asset manager.

**Comment by fireproofsocks** [comment]
Sure, please feel free to update the version on MODX.com -- that would be appreciated.  The bounty (as you may have inferred) was not sufficient to get this onto my radar, but if you've got people using it, you're better off than me.

**Comment by Mark-H** [comment]
I've issued a 1.2 release on MODX.com. Took me longer than I anticipated having never used repoman before, but from my testing it seems to be working alright! https://modx.com/extras/package/assetmanager

Please let me know if anyone is experiencing issues with the build.

**Comment by Mark-H** [comment]
When this issue is marked as closed the bounty can be claimed.

**Comment by fireproofsocks** [comment]
I merged your PR, closing the issue -- let me know if any other changes are required.

**Comment by Mark-H** [comment]
Thank you!
