### ISSUE TITLE
[Urgent] AssetManager doesn't show photos after update

### ISSUE THREAD

**Issue by alikmster** [craftsmancoding/assetmanager#86]
Today I've updated the component to 1.2.0 (wow, it's alive), but no photos are visible on the website and I don't get any error.

**Comment by Mark-H** [comment]
Any errors in the MODX error log?

**Comment by alikmster** [comment]
I would be happy if so, but no.

**Comment by Mark-H** [comment]
Hmm, I'm not seeing [anything in the code changes since 1.1.1](https://github.com/craftsmancoding/assetmanager/compare/2fd515f57e821643c9239bbcfb9178c78bf59915...master) that would explain such a break...

**Comment by Mark-H** [comment]
In the getPageAssets snippet, change line 72-76 with the following:

```` php

$innerTpl = $modx->getOption('innerTpl', $scriptProperties, '<li><img src="[[+Asset.url]]" width="[[+Asset.width]]" height="[[+Asset.height]]" alt="[[+Asset.alt]]" /></li>', true);
$outerTpl = $modx->getOption('outerTpl', $scriptProperties, '<ul>[[+content]]</ul>', true);
$firstTpl = $modx->getOption('firstTpl', $scriptProperties, $innerTpl, true);
$lastTpl = $modx->getOption('lastTpl', $scriptProperties, $innerTpl, true);
$onOne = $modx->getOption('onOne', $scriptProperties, 'innerTpl', true);
````

That seems to help get stuff to show up.

I suspect that something I did in preparing the build caused it to install snippet properties, which it may not have done before, and the snippet was not built with those in mind. It's checking properties with the assumption that if they are set, that they have the value it needs to use, rather than checking if it actually has a value. 

The &is_image and &group property may also be needed on your snippet call.

**Comment by alikmster** [comment]
Ok, I'll check and reply. Thank you!

**Comment by Mark-H** [comment]
Please see the full changes I've made in #87 and let me know if that fixes it. If so I can push out a 1.2.1 build today.

**Comment by alikmster** [comment]
Yes, now everything works!

**Comment by Mark-H** [comment]
Excellent, I'll push out a 1.2.1 release.

**Comment by fireproofsocks** [comment]
Marking closed.
